name: Continuous Integration Workflow

on:
  pull_request:
    branches:
      -  main

defaults:
  run:
    shell: bash
    working-directory: ./web

jobs:

  test:
    name: 'Run unit tests'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        name: 'Checkout Repository'
      
      - name: "Install Dependencies"
        run: npm install
      
      - name: "Run Tests"
        run: npm run test
  
  lint:
    name: "Run Linter"
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v4
      name: 'Checkout Repository'

    - name: "Install Dependencies"
      run: npm install
    
    - name: " Run Linter"
      run: npx standard -v

  deploy:
    name: 'Deploy to Staging Environment'
    runs-on: ubuntu-latest
    needs: [test, lint]  # This ensures that the deploy job runs after the test and lint jobs
    steps:
      - uses: actions/checkout@v4
        name: 'Checkout Repository'

      - name: 'Set up Node.js'
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Use the Node.js version that suits your app

      - name: 'Install Dependencies'
        run: npm install

      - name: 'Build the app'
        run: npm run build  # Run your build command if you have one, or skip if not needed
      
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        with:
          app-name: <YOUR_APP_NAME>  # Replace with your Azure Web App name
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}  # The secret containing your publish profile
          package: '.' 




